// Generated by CoffeeScript 1.12.6
(function() {
  this.Shopping_Carts = new Meteor.Collection("shopping_carts");

  this.Schemas = {};

  Schemas.shopping_carts = new SimpleSchema({
    parent_user_id: {
      type: String,
      optional: false
    },
    status: {
      type: String,
      optional: true
    },
    menu_options_selected_by_user: {
      type: [String],
      optional: true
    }
  });

  Shopping_Carts.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    },
    remove: function() {
      return true;
    }
  });

}).call(this);

//# sourceMappingURL=shopping_carts.js.map
